name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Server Test
        working-directory: ./backend
        run: node server.js &

      - name: Stop Server
        run: echo "Backend started successfully"